### ISSUE TITLE
怎么使用，看半天不懂，用JAVA 执行也没有用

### ISSUE THREAD

**Issue by cuican008** [zz0116/autoLivesOne#1]
怎么使用，看半天不懂，用JAVA 执行也没有用

**Comment by cuican008** [comment]
C:\Users\cui\autoLivesOne-master\src\main\java\com\zyz\learn\autolivesone>Java Auto
Exception in thread "main" java.lang.NoClassDefFoundError: Auto (wrong name: com/zyz/learn/autolivesone/Auto)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by cuican008** [comment]
删除第一行包文件即可
